name: rtorrent docker CI

on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build docker image
      run: docker build . --file Dockerfile --tag ghcr.io/ynadji/rtorrent:latest
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push to GHCR
      run: docker push ghcr.io/ynadji/rtorrent:latest
